# Numpy

In [3]:
import numpy as np

# Creating Arrays

In [4]:
my_list = [1, 2, 3]
x = np.array(my_list)
x

array([1, 2, 3])

In [5]:
y = np.array([4, 8, 9])
y

array([4, 8, 9])

In [7]:
m = np.array([[8, 3, 7], [3, 9, 4]])
m

array([[8, 3, 7],
       [3, 9, 4]])

In [8]:
m.shape

(2, 3)

In [53]:
n = np.arange(0, 30, 2)
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [55]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [56]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [59]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.diag((y))

array([[4, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

In [66]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [77]:
p = np.ones([2 ,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [81]:
np.vstack([p, 9*p])

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [82]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [83]:
x + y

array([ 5, 10, 12])

In [84]:
x * y

array([ 4, 16, 27])

In [85]:
x ** 2

array([1, 4, 9])

In [87]:
x.dot(y)

47

In [88]:
z = np.array([y, y**2])

In [89]:
z

array([[ 4,  8,  9],
       [16, 64, 81]])

In [91]:
z.shape

(2, 3)

In [92]:
z.T

array([[ 4, 16],
       [ 8, 64],
       [ 9, 81]])

In [93]:
z.T.shape

(3, 2)

In [94]:
z.dtype

dtype('int64')

In [95]:
z = z.astype('f')
z

array([[ 4.,  8.,  9.],
       [16., 64., 81.]], dtype=float32)

In [97]:
z.dtype

dtype('float32')

In [101]:
a = np.array([-4, -2, 1, 3,5])

In [102]:
a

array([-4, -2,  1,  3,  5])

In [104]:
a.sum()

3

In [106]:
a.min()

-4

In [107]:
a.max()

5

In [108]:
a.mean()

0.6

In [109]:
a.std()

3.2619012860600183

In [111]:
z.argmax()

4

In [112]:
z.argmin()

0

# Indexing / Slicing

In [113]:
s =  np.arange(13)**2

In [114]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [118]:
s[0], s[4], s[0:4]

(0, 16, array([0, 1, 4, 9]))

In [121]:
s[1:5]

array([ 1,  4,  9, 16])

In [123]:
s[-4:]

array([ 81, 100, 121, 144])

In [124]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [125]:
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [129]:
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [130]:
r[3,3]

21

In [133]:
r[3, 3:6]

array([21, 22, 23])

In [135]:
r[-5, ::2]

array([ 6,  8, 10])

In [136]:
r[-4]

array([12, 13, 14, 15, 16, 17])

In [137]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [141]:
r[-1, ::2]

array([30, 32, 34])

In [142]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [144]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [146]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [147]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [148]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [151]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [154]:
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating Over Arrays

In [157]:
test = np.random.randint(0, 10, (4,3))
test

array([[0, 2, 1],
       [9, 1, 9],
       [2, 0, 8],
       [0, 0, 5]])

In [158]:
for row in test:
        print(row)

[0 2 1]
[9 1 9]
[2 0 8]
[0 0 5]


In [160]:
for i in range(len(test)):
    print(test[i])

[0 2 1]
[9 1 9]
[2 0 8]
[0 0 5]


In [161]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [0 2 1]
row 1 is [9 1 9]
row 2 is [2 0 8]
row 3 is [0 0 5]


In [162]:
test2 = test ** 2
test2

array([[ 0,  4,  1],
       [81,  1, 81],
       [ 4,  0, 64],
       [ 0,  0, 25]])

In [163]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[0 2 1] + [0 4 1] = [0 6 2]
[9 1 9] + [81  1 81] = [90  2 90]
[2 0 8] + [ 4  0 64] = [ 6  0 72]
[0 0 5] + [ 0  0 25] = [ 0  0 30]
